[tools]
python = "3.12"
node = "latest"
neovim = "stable"
eza = "0.23.4"
fzf = "latest"
carapace = "latest"
atuin = "latest"
delta = "latest"
lazygit = "latest"
fd = "latest"
ripgrep = "latest"
uv = "latest"
bat = "latest"
"github:Giammarco-Ferranti/deja" = "latest"
pnpm = "latest"
pipx = "latest"
"aqua:github/copilot-cli" = "latest"
